version: "3"
services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=food_helper
    ports:
      - "3306:3306"
    restart: always
  springboot-backend:
    environment:
      - "SPRING_PROFILES_ACTIVE=test"
    restart: on-failure
    ports:
      - "8080:8080"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - database




