version: "3"
services:
  mysql-database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=A.123456
      - MYSQL_DATABASE=food_helper
    ports:
      - "3306:3306"
    restart: always
  springboot-backend:
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-database




