spring:
    datasource:
        url: jdbc:mysql://localhost:3306/food_helper?useTimezone=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        jpa:
            show-sql: true
            hibernate:
                ddl-auto: validate
    liquibase:
        change-log: classpath:liquibase-changelog.xml
    config:
        import: file:env.properties
    mail:
        host: smtp.gmail.com
        username: ${EMAIL_ADDRESS}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    port: 587
                    starttls:
                        enable: true
                transport:
                    protocol: smtp

resilience4j.circuitbreaker:
    configs:
        default:
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 10
            waitDurationInOpenState: 10s
            failureRateThreshold: 60
            minimumNumberOfCalls: 3
            eventConsumerBufferSize: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            registerHealthIndicator: true
            ignoreExceptions:
                - org.springframework.security.access.AccessDeniedException

management:
    health:
        circuitbreakers:
            enabled: true
        endpoints:
            web:
                exposure:
                    include: health
        endpoint:
            health:
                show-details: when-authorized

server:
    error:
        whitelabel:
            enabled: false

api-key:
    spoonacularValue: ${SPOONACULAR_KEY}

---

spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url: jdbc:mysql://database:3306/food_helper?useTimezone=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true